/**
 * Created by erichua on 04/01/2018.
 */
import ServerPrefixType from '../../api/ServerPrefixType'
import METHOD from '../../api/Method'
import { CGI as globalCGI } from 'apps/webankPro/api'

export default {
  ...globalCGI,
  requestHjProGrayInfo: {
    // mockable: true,
    method: METHOD.GET,
    path: 'check_whitelist/hjpro',
    desc: 'hj-pro的业务灰度接口',
    cacheMaxAgeInMs: 0,
    request: {},
    response: {
      whiteList: [
        {
          'type': 82, // 81 or 82
          'itemId': '',
          'inFlag': true,
          'idType': 'ecif' // ecif or openid
        }
      ]
    }
  },
  requestGrayInfo: {
    // mockable: true,
    method: METHOD.GET,
    path: 'check_whitelist/v3',
    desc: '通用的业务灰度接口',
    request: {
      cycle: [
        {
          'type': 69,
          'itemId': 'calendar',
          'idType': 'ecif'
        }
      ]
    },
    response: {
      whiteList: [
        {
          'type': 69,
          'itemId': 'calendar',
          'inFlag': true,
          'idType': 'ecif'
        }
      ]
    }
  },
  requestNewGrayInfo: {
    // mockable: true,
    method: METHOD.GET,
    path: 'check_whitelist/v4',
    desc: '通用的业务灰度接口v4(支持黑名单)',
    request: {
      cycle: [
        {
          'type': 69,
          'itemId': 'calendar',
          'idType': 'ecif'
        }
      ]
    },
    response: {
      whiteList: [
        {
          'type': 69,
          'itemId': 'calendar',
          'inFlag': true,
          'idType': 'ecif'
        }
      ]
    }
  },
  // Feedback
  requestFeedbackRedDot: {
    path: 'dbdcss/feedback/querynotreadmsg',
    desc: '查询反馈系统的红点信息',
    cacheMaxAgeInMs: 0,
    cgiPrefix: ServerPrefixType.Q_CLOUD_FB,
    method: METHOD.GET,
    request: {},
    response: {
      new_msgtype_count: 1, // 返回有新消息msgtype的数目
      new_msgtype_list: [
        {
          'msg_type': 'FEEDBACK', // 暂时只有FEEDBACK类型，列表为空说明没新消息
          'position_list': ['sidebar'] // 红点所在位置，如果为空默认用客户端位置
        }
      ]
    }
  },
  personalInfo: {
    method: METHOD.GET,
    path: 'user/query_personnal_info/v2', // 改用v2接口,包含信用卡绑卡信息
    desc: '个人信息'
  },
  userWealthV3: {
    // mockable: true,
    path: 'query/wealth/all/v3',
    desc: '资产接口',
    request: {},
    response: {'amount_distribution': {'balance_amount': 97321.81, 'deposit_amount': 70000, 'fund_amount': 2211, 'gold_amount': 45258.06, 'gold_weight': 165.35645807, 'insurance_amount': 0, 'long_finance_amount': 5502, 'margin_amount': 0, 'short_finance_amount': 2100, 'structure_amount': 6900, 'total_amount': 501286337.25, 'webank_amount': 501057044.38, 'wecard_amount': 0}, 'core_account': {'amount': 501078146.38, 'available_amount': 501057044.38, 'behalf_flag': '0', 'effective_rate': 0.35, 'freezing_list': [{'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161108'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161108'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161109'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161113'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161115'}, {'amout': 2000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161118'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161119'}, {'amout': 200, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161122'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 5000, 'flag': '0', 'freezing_code': '22', 'reason': '理财购买', 'satrt_date': '20161202'}, {'amout': 2, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161202'}, {'amout': 5000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161203'}, {'amout': 200, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161208'}, {'amout': 500, 'flag': '0', 'freezing_code': '22', 'reason': '理财购买', 'satrt_date': '20170225'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20170401'}, {'amout': 500, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20170401'}], 'last_interest_paid_date': '20170621', 'next_interest_paid_date': '20170921', 'opendate': '20161108'}, 'finance_wealth': {'balance_cycle': [{'available_vol': 97321.81, 'day_buy_amount': 1921, 'day_buy_num': 13, 'day_max_buy_amount': 0, 'day_max_buy_num': 111, 'day_max_redeem_amount': 3000000, 'day_max_redeem_num': 111, 'day_redeem_amount': 1, 'day_redeem_num': 1, 'last_income': 2.01, 'prod_code': '001234', 'prod_name': '国金基金众盈货币', 'total_income': 2.01, 'total_vol': 97445.81}], 'bank_cycle': [{'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 5500, 'can_buy': '1', 'can_modify_dividend': '0', 'can_redeem': '0', 'end_market_date': '20170630', 'prod_code': 'TEMP01', 'prod_name': '哈哈哈', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'rollflag': '3', 'total_income': 0, 'total_vol': 0, 'trans_frozen_vol': 0}], 'fund_cycle': [{'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 1111, 'can_buy': '0', 'can_modify_dividend': '0', 'can_redeem': '1', 'convert_status': '0', 'dividend_method': '1', 'end_market_date': '', 'fee_method': '0', 'first_buy_date': '20161209', 'first_buy_time': '152011', 'income_rate': 0, 'last_buy_date': '20170124', 'last_buy_time': '114123', 'net_value': 1.15, 'net_value_date': '20160817', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': '090001', 'prod_name': '大成价值', 'prod_type': '1', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '', 'ta_account': '000009288033', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 0, 'total_net_value': 1.57, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '1'}, {'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 1100, 'can_buy': '1', 'can_modify_dividend': '0', 'can_redeem': '0', 'convert_status': '0', 'dividend_method': '1', 'end_market_date': '', 'fee_method': '1', 'first_buy_date': '20161220', 'first_buy_time': '194720', 'income_rate': 0, 'last_buy_date': '20161228', 'last_buy_time': '094051', 'net_value': 1.1, 'net_value_date': '20160303', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': '091002', 'prod_name': '大成债券正常更新', 'prod_type': '1', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '', 'ta_account': '000009288033', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 0, 'total_net_value': 1.1, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '1'}, {'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 2, 'can_buy': '0', 'can_modify_dividend': '0', 'can_redeem': '1', 'convert_status': '0', 'dividend_method': '1', 'end_market_date': '20170430', 'fee_method': '0', 'first_buy_date': '20170119', 'first_buy_time': '171136', 'income_rate': 0, 'last_buy_date': '20170119', 'last_buy_time': '171136', 'net_value': 1, 'net_value_date': '20170329', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': 'QQ1206', 'prod_name': '齐鲁稳固21', 'prod_type': '3', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '1', 'ta_account': 'T_0126295001', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 0, 'total_net_value': 0, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '0'}, {'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 100, 'can_buy': '0', 'can_modify_dividend': '0', 'can_redeem': '1', 'convert_status': '3', 'dividend_method': '0', 'end_market_date': '20170215', 'fee_method': '0', 'first_buy_date': '20161228', 'first_buy_time': '094253', 'income_rate': 0.025, 'last_buy_date': '20161228', 'last_buy_time': '094253', 'net_value': 1, 'net_value_date': '20160713', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': 'BC0013', 'prod_name': '方正看跌产品', 'prod_type': '3', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '3', 'ta_account': '0000BC290005', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 0, 'total_net_value': 1, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '1'}, {'available_vol': 0, 'avg_cost': 50000, 'buy_in_trans': 5000, 'can_buy': '0', 'can_modify_dividend': '1', 'can_redeem': '1', 'convert_status': '3', 'dividend_method': '1', 'end_market_date': '20170205', 'fee_method': '0', 'first_buy_date': '20170120', 'first_buy_time': '151653', 'income_rate': 0, 'last_buy_date': '20170120', 'last_buy_time': '151653', 'net_value': 1, 'net_value_date': '20161219', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': 'BC1121', 'prod_name': '方正看跌产品一', 'prod_type': '3', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '3', 'ta_account': '0000BC290005', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 150, 'total_net_value': 0, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '3'}, {'available_vol': 0, 'avg_cost': 0, 'buy_in_trans': 1800, 'can_buy': '0', 'can_modify_dividend': '0', 'can_redeem': '1', 'convert_status': '3', 'dividend_method': '0', 'end_market_date': '20170127', 'fee_method': '0', 'first_buy_date': '20161209', 'first_buy_time': '163006', 'income_rate': 0.025, 'last_buy_date': '20170317', 'last_buy_time': '165746', 'net_value': 1, 'net_value_date': '20160713', 'pledge_availablevol': 0, 'pledge_vol': 0, 'prod_code': 'BCC009', 'prod_name': '方正浮动收益', 'prod_type': '3', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '3', 'ta_account': '0000BC290005', 'ta_frozen_vol': 0, 'total_amount': 0, 'total_income': 0, 'total_net_value': 1, 'total_vol': 0, 'trans_frozen_vol': 0, 'transfer_status': '1'}], 'margin_asset_cycle': [], 'pmes_cycle': [{'available_vol': 143.35645807, 'avg_cost': 266.97, 'interest_rate': 0.015, 'last_close_price': 273.7, 'last_income': 0.00163971, 'last_income_date': '20161231', 'pm_acct_no': 'CK001000100201612150000000002', 'prod_code': '10001', 'prod_name': '微众金活期', 'prod_type': 'C', 'total_income': 0.03776159, 'total_vol': 165.35645807}], 'ptx_cycle': [{'available_vol': 1100, 'buy_in_trans': 1100, 'confirmed_no_income_cycle': [], 'income_view_flag': '0', 'last_income': 0, 'last_income_date': '0', 'net_value': 1, 'net_value_date': '20161206', 'prod_code': 'ZA20161206', 'prod_name': '众赢二号', 'prod_status': '1', 'prod_type': 'ZAX', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'refund_income': 0, 'rollflag': '3', 'ta_account': 'ZA', 'ta_no': 'ZA', 'total_amount': 1100, 'total_income': 0, 'total_vol': 1100}, {'available_vol': 1000, 'buy_in_trans': 0, 'income_view_flag': '0', 'last_income': 0, 'last_income_date': '0', 'net_value': 1, 'net_value_date': '20170302', 'prod_code': 'ATltx', 'prod_name': '投连险自动化', 'prod_status': '1', 'prod_type': 'TLX', 'redeem_in_trans_confirmed': 0, 'redeem_in_trans_confirming': 0, 'refund_amount': 0, 'rollflag': '3', 'total_amount': 1000, 'total_income': 0, 'total_vol': 1000}], 'quote_repo_cycle': [], 'system_time': '20170329204020', 'webank_card_cycle': [{'account_balance': 10000, 'account_status': 'A', 'available_balance': 10000, 'currency_code': '01', 'deposit_term': '3M', 'deposit_type': '01', 'draw_amount_per_term': 0, 'effective_rate': 1.32, 'effective_rate_str': '1.32', 'expiry_date': '20170208', 'fixed_current_flag': '1', 'interest_paid': 0, 'prod_code': '11200401-1', 'product_id': '11200401', 'refund_type': '03', 'reinverst_term': '3M', 'reinvest_mode': '1', 'subaccount_serial_no': '00002', 'to_draw_times': 0, 'value_date': '20161108'}, {'account_balance': 10000, 'account_status': 'A', 'available_balance': 10000, 'currency_code': '01', 'deposit_term': '3M', 'deposit_type': '01', 'draw_amount_per_term': 0, 'effective_rate': 1.32, 'effective_rate_str': '1.32', 'expiry_date': '20170208', 'fixed_current_flag': '1', 'interest_paid': 0, 'prod_code': '11200401-1', 'product_id': '11200401', 'refund_type': '02', 'reinvest_mode': '0', 'subaccount_serial_no': '00003', 'to_draw_times': 0, 'value_date': '20161108'}, {'account_balance': 0, 'account_status': 'C', 'available_balance': 0, 'currency_code': '01', 'deposit_term': '3M', 'deposit_type': '01', 'draw_amount_per_term': 0, 'effective_rate': 1.32, 'effective_rate_str': '1.32', 'expiry_date': '20170213', 'fixed_current_flag': '1', 'interest_paid': 0, 'prod_code': '11200401-1', 'product_id': '11200401', 'refund_type': '03', 'reinverst_term': '3M', 'reinvest_mode': '1', 'subaccount_serial_no': '00004', 'to_draw_times': 0, 'value_date': '20161113'}, {'account_balance': 0, 'account_status': 'C', 'available_balance': 0, 'currency_code': '01', 'deposit_term': '1Y', 'deposit_type': '01', 'draw_amount_per_term': 0, 'effective_rate': 1.8, 'effective_rate_str': '1.80', 'expiry_date': '20171118', 'fixed_current_flag': '1', 'interest_paid': 0, 'prod_code': '11200401-1', 'product_id': '11200401', 'refund_type': '03', 'reinverst_term': '1Y', 'reinvest_mode': '1', 'subaccount_serial_no': '00005', 'to_draw_times': 0, 'value_date': '20161118'}, {'account_balance': 50000, 'account_status': 'A', 'available_balance': 50000, 'currency_code': '01', 'deposit_term': '5Y', 'deposit_type': '03', 'draw_amount_per_term': 0, 'effective_rate': 5.05, 'effective_rate_str': '5.05', 'expiry_date': '20220815', 'fixed_current_flag': '1', 'interest_paid': 0, 'last_interest_paid_date': '20170815', 'next_interest_paid_date': '20170915', 'prod_code': '11201401-1', 'product_id': '11201401', 'refund_type': '11', 'reinvest_mode': '0', 'subaccount_serial_no': '00006', 'to_draw_times': 0, 'value_date': '20170815'}], 'wnx_cycle': []}}
  },
  userWealthV4: {
//    mockable: true,
    path: 'query/wealth/all/v5',
    desc: '资产接口(去掉存款详细列表)',
    request: {},
    response: {'amount_distribution': {'balance_amount': 97321.81, 'deposit_amount': 70000, 'fund_amount': 2211, 'gold_amount': 45258.06, 'gold_weight': 165.35645807, 'insurance_amount': 0, 'long_finance_amount': 5502, 'margin_amount': 0, 'short_finance_amount': 2100, 'structure_amount': 6900, 'total_amount': 501286337.25, 'webank_amount': 501057044.38, 'wecard_amount': 0},
      'core_account': {'amount': 501078146.38, 'available_amount': 501057044.38, 'behalf_flag': '0', 'effective_rate': 0.35, 'freezing_list': [{'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161108'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161108'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161109'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161113'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161115'}, {'amout': 2000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161118'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161119'}, {'amout': 200, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'satrt_date': '20161122'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161122'}, {'amout': 1000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161123'}, {'amout': 5000, 'flag': '0', 'freezing_code': '22', 'reason': '理财购买', 'satrt_date': '20161202'}, {'amout': 2, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161202'}, {'amout': 5000, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161203'}, {'amout': 200, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20161208'}, {'amout': 500, 'flag': '0', 'freezing_code': '22', 'reason': '理财购买', 'satrt_date': '20170225'}, {'amout': 100, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20170401'}, {'amout': 500, 'flag': '0', 'freezing_code': '22', 'reason': '基金购买', 'satrt_date': '20170401'}], 'last_interest_paid_date': '20170621', 'next_interest_paid_date': '20170921', 'opendate': '20161108'},
      'finance_wealth': {'balance_cycle': [
        {
          'cust_name': '基金跳转',
          'ta_account': '20170213K00338137',
          'card_no': '6236330070000009157',
          'acct_no': '6236330070000009157',
          'prod_code': '000397',
          'prod_name': '汇添富货币基金',
          'total_vol': 75262.37,
          'available_vol': 75262.37,
          'total_income': 0,
          'last_income': 0,
          'day_buy_num': 0,
          'day_max_buy_num': 100,
          'day_buy_amount': 0,
          'day_max_buy_amount': 0,
          'day_redeem_num': 0,
          'day_max_redeem_num': 100,
          'day_redeem_amount': 600,
          'day_max_redeem_amount': 10000,
          'redeem_in_trans': 0,
          'frozen_vol': 0,
          'uniq_tano': '47',
          'uniq_prod_code': '000397',
          'have_vol_flag': '0'
        }
      ],
        'fund_cycle': [
          {
            'ta_account': 'T_0808372012',
            'prod_code': '250002',
            'prod_name': '国联安债券',
            'dividend_method': '1',
            'convert_status': '0',
            'transfer_status': '1',
            'can_buy': '1',
            'can_redeem': '0',
            'can_modify_dividend': '0',
            'total_vol': 0,
            'available_vol': 0,
            'trans_frozen_vol': 0,
            'ta_frozen_vol': 0,
            'fee_method': '0',
            'total_amount': 0,
            'income_rate': 0,
            'total_income': 0,
            'net_value': 1.001,
            'total_net_value': 1.051,
            'net_value_date': '20160808',
            'end_market_date': '',
            'prod_type': '1',
            'rollflag': '',
            'redeem_in_trans_confirmed': 0,
            'buy_in_trans': 1000,
            'redeem_in_trans_confirming': 0,
            'avg_cost': 0,
            'refund_amount': 0,
            'first_buy_date': '20180807',
            'first_buy_time': '232233',
            'last_buy_date': '20180807',
            'last_buy_time': '232233',
            'pledge_availablevol': 0,
            'pledge_vol': 0,
            'cash_div_in_trans': 0,
            'vol_div_in_trans': 0,
            'pledge_dividendmethod': '2',
            'structured': '0',
            'fund_pattern': '1'
          },
          {
            'ta_account': 'T_0904374017',
            'prod_code': '668881',
            'prod_name': '广发弘利1',
            'dividend_method': '1',
            'convert_status': '3',
            'transfer_status': '3',
            'can_buy': '0',
            'can_redeem': '1',
            'can_modify_dividend': '1',
            'total_vol': 0,
            'available_vol': 0,
            'trans_frozen_vol': 0,
            'ta_frozen_vol': 0,
            'fee_method': '0',
            'total_amount': 0,
            'income_rate': 0,
            'total_income': 0,
            'net_value': 0.9991,
            'total_net_value': 1.8888,
            'net_value_date': '20180903',
            'end_market_date': '20181005',
            'prod_type': '3',
            'rollflag': '0',
            'redeem_in_trans_confirmed': 0,
            'buy_in_trans': 50000,
            'redeem_in_trans_confirming': 0,
            'avg_cost': 0,
            'refund_amount': 0,
            'first_buy_date': '20180904',
            'first_buy_time': '112233',
            'last_buy_date': '20180904',
            'last_buy_time': '112233',
            'pledge_availablevol': 0,
            'pledge_vol': 0,
            'cash_div_in_trans': 0,
            'vol_div_in_trans': 0,
            'pledge_dividendmethod': '2',
            'structured': '0',
            'fund_pattern': '2'
          },
          {
            'ta_account': 'T_0904374016',
            'prod_code': 'YJ0002',
            'prod_name': '齐鲁固收1期',
            'dividend_method': '1',
            'convert_status': '3',
            'transfer_status': '3',
            'can_buy': '0',
            'can_redeem': '1',
            'can_modify_dividend': '0',
            'total_vol': 0,
            'available_vol': 0,
            'trans_frozen_vol': 0,
            'ta_frozen_vol': 0,
            'fee_method': '1',
            'total_amount': 0,
            'income_rate': 0,
            'total_income': 0,
            'net_value': 1,
            'total_net_value': 0,
            'net_value_date': '20180904',
            'end_market_date': '20180926',
            'prod_type': '3',
            'rollflag': '0',
            'redeem_in_trans_confirmed': 0,
            'buy_in_trans': 50000,
            'redeem_in_trans_confirming': 0,
            'avg_cost': 0,
            'refund_amount': 0,
            'first_buy_date': '20180904',
            'first_buy_time': '112233',
            'last_buy_date': '20180904',
            'last_buy_time': '112233',
            'pledge_availablevol': 0,
            'pledge_vol': 0,
            'pledge_dividendmethod': '2',
            'structured': '0',
            'fund_pattern': '1'
          },
          {
            'ta_account': 'T_0213297003',
            'prod_code': 'BCC009',
            'prod_name': '方正浮动收益',
            'dividend_method': '0',
            'convert_status': '3',
            'transfer_status': '1',
            'can_buy': '0',
            'can_redeem': '1',
            'can_modify_dividend': '0',
            'total_vol': 0,
            'available_vol': 0,
            'trans_frozen_vol': 0,
            'ta_frozen_vol': 0,
            'fee_method': '0',
            'total_amount': 0,
            'income_rate': 0.025,
            'total_income': 0,
            'net_value': 1,
            'total_net_value': 1,
            'net_value_date': '20160713',
            'end_market_date': '20170701',
            'prod_type': '3',
            'rollflag': '3',
            'redeem_in_trans_confirmed': 0,
            'buy_in_trans': 100,
            'redeem_in_trans_confirming': 0,
            'avg_cost': 0,
            'refund_amount': 0,
            'first_buy_date': '20170213',
            'first_buy_time': '151739',
            'last_buy_date': '20170213',
            'last_buy_time': '151739',
            'pledge_availablevol': 0,
            'pledge_vol': 0,
            'pledge_dividendmethod': '2',
            'structured': '0',
            'fund_pattern': '1'
          },
          {
            'ta_account': 'T_0816372015',
            'prod_code': '666660',
            'prod_name': '结构性存款A',
            'dividend_method': '1',
            'convert_status': '3',
            'transfer_status': '3',
            'can_buy': '0',
            'can_redeem': '1',
            'can_modify_dividend': '0',
            'total_vol': 0,
            'available_vol': 0,
            'trans_frozen_vol': 0,
            'ta_frozen_vol': 0,
            'fee_method': '0',
            'total_amount': 0,
            'income_rate': 0,
            'total_income': 0,
            'net_value': 1,
            'total_net_value': 1,
            'net_value_date': '20180726',
            'end_market_date': '20190118',
            'prod_type': '3',
            'rollflag': '0',
            'redeem_in_trans_confirmed': 0,
            'buy_in_trans': 10000,
            'redeem_in_trans_confirming': 0,
            'avg_cost': 0,
            'refund_amount': 0,
            'first_buy_date': '20180816',
            'first_buy_time': '112233',
            'last_buy_date': '20180816',
            'last_buy_time': '112233',
            'pledge_availablevol': 0,
            'pledge_vol': 0,
            'pledge_dividendmethod': '2',
            'structured': '1',
            'fund_pattern': '1'
          }
        ],
        'wnx_cycle': [],
        'bank_cycle': [],
        'ptx_cycle': [],
        'pmes_cycle': [
          {
            'pm_acct_no': 'CK001000100201703160000000001',
            'prod_name': '微众金活期',
            'prod_type': 'C',
            'prod_code': '10001',
            'total_vol': 1,
            'available_vol': 1,
            'avg_cost': 268.17,
            'total_income': 0,
            'last_income': 0,
            'last_income_date': '20170108',
            'interest_rate': 0.015
          }
        ],
        'margin_asset_cycle': [],
        'webank_card_cycle': [],
        'quote_repo_cycle': [],
        'deposit_prod_cycle': [
          {
            'product_id': '11200301',
            'deposit_type': '01',
            'total_records': 1,
            'currency_code': '01',
            'account_balance': 174381.5,
            'available_balance': 63081.5
          },
          {
            'product_id': '11200401',
            'total_records': 16,
            'deposit_type': '02',
            'currency_code': '01',
            'account_balance': 10500,
            'available_balance': 10500
          },
          {
            'product_id': '11200501',
            'deposit_type': '03',
            'total_records': 1,
            'currency_code': '01',
            'account_balance': 0,
            'available_balance': 0
          },
          {
            'product_id': '11201401',
            'total_records': 7,
            'deposit_type': '28',
            'currency_code': '01',
            'account_balance': 29960,
            'available_balance': 29960
          },
          {
            'product_id': '11201601',
            'deposit_type': '30',
            'total_records': 1,
            'currency_code': '01',
            'account_balance': 0,
            'available_balance': 0
          },
          {
            'product_id': '11203001',
            'deposit_type': '01',
            'total_records': 1,
            'currency_code': '01',
            'account_balance': 100,
            'available_balance': 100
          }
        ],
        'assets_excep_flag': 0
      }}
  },
  userDepositList: {
//    mockable: true,
    path: 'query/wealth/deposit/detail',
    desc: '存单明细查询',
    cacheMaxAgeInMs: 0,
    method: METHOD.GET,
    request: {},
    response: {
      'total_records': 27,
      'webank_card_cycle': [
        {
          'subaccount_serial_no': '00001',
          'currency_code': '01',
          'product_id': '11200301',
          'deposit_type': '00',
          'deposit_term': '0D',
          'account_status': 'A',
          'account_balance': 174381.5,
          'available_balance': 63081.5,
          'value_date': '20161205',
          'effective_rate': 0.3,
          'to_draw_times': 0,
          'last_interest_paid_date': '20380621',
          'next_interest_paid_date': '20410220',
          'fixed_current_flag': '0',
          'interest_paid': 0
        },
        {
          'subaccount_serial_no': '00002',
          'currency_code': '01',
          'product_id': '11200501',
          'deposit_type': '02',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20161205',
          'effective_rate': 3.12,
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0
        },
        {
          'subaccount_serial_no': '00003',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20181001',
          'expiry_date': '20231001',
          'effective_rate': 5.05,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20181001',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '14'
        },
        {
          'subaccount_serial_no': '00004',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20181001',
          'expiry_date': '20231001',
          'effective_rate': 5.05,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20181001',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '11'
        },
        {
          'subaccount_serial_no': '00005',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20181001',
          'expiry_date': '20231001',
          'effective_rate': 5.05,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20181001',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '11'
        },
        {
          'subaccount_serial_no': '00006',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 12480,
          'available_balance': 12480,
          'value_date': '20191104',
          'expiry_date': '20241104',
          'effective_rate': 5,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20260204',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 3900.01,
          'refund_type': '14'
        },
        {
          'subaccount_serial_no': '00007',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20191213',
          'expiry_date': '20241213',
          'effective_rate': 5,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20191213',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '14'
        },
        {
          'subaccount_serial_no': '00008',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 12480,
          'available_balance': 12480,
          'value_date': '20200219',
          'expiry_date': '20250219',
          'effective_rate': 5,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20260119',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 3692.01,
          'refund_type': '14'
        },
        {
          'subaccount_serial_no': '00009',
          'currency_code': '01',
          'product_id': '11201401',
          'deposit_type': '03',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 5000,
          'available_balance': 5000,
          'value_date': '20220619',
          'expiry_date': '20270619',
          'effective_rate': 4.875,
          'reinvest_mode': '0',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'last_interest_paid_date': '20260119',
          'next_interest_paid_date': '20270920',
          'fixed_current_flag': '1',
          'interest_paid': 873.42,
          'refund_type': '11'
        },
        {
          'subaccount_serial_no': '00010',
          'currency_code': '01',
          'product_id': '11201601',
          'deposit_type': '02',
          'deposit_term': '5Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350711',
          'expiry_date': '20400711',
          'effective_rate': 4.1,
          'reinvest_mode': '1',
          'reinverst_term': '5Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00011',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '3Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350729',
          'expiry_date': '20380729',
          'effective_rate': 4.1,
          'reinvest_mode': '1',
          'reinverst_term': '3Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00012',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '1Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350729',
          'expiry_date': '20360729',
          'effective_rate': 1.8,
          'reinvest_mode': '1',
          'reinverst_term': '1Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00013',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '2Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350729',
          'expiry_date': '20370729',
          'effective_rate': 3.12,
          'reinvest_mode': '1',
          'reinverst_term': '2Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00014',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '1Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350729',
          'expiry_date': '20360729',
          'effective_rate': 1.8,
          'reinvest_mode': '1',
          'reinverst_term': '1Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00015',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '1Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20350729',
          'expiry_date': '20360729',
          'effective_rate': 1.8,
          'reinvest_mode': '1',
          'reinverst_term': '1Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00016',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '1Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20351122',
          'expiry_date': '20361122',
          'effective_rate': 1.8,
          'reinvest_mode': '1',
          'reinverst_term': '1Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00017',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '3M',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20351122',
          'expiry_date': '20360222',
          'effective_rate': 1.32,
          'reinvest_mode': '1',
          'reinverst_term': '3M',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00018',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '3M',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20351122',
          'expiry_date': '20360222',
          'effective_rate': 1.32,
          'reinvest_mode': '1',
          'reinverst_term': '3M',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00019',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '2Y',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20351122',
          'expiry_date': '20371122',
          'effective_rate': 3.12,
          'reinvest_mode': '1',
          'reinverst_term': '2Y',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        },
        {
          'subaccount_serial_no': '00020',
          'currency_code': '01',
          'product_id': '11200401',
          'deposit_type': '01',
          'deposit_term': '6M',
          'account_status': 'C',
          'account_balance': 0,
          'available_balance': 0,
          'value_date': '20351122',
          'expiry_date': '20360522',
          'effective_rate': 1.56,
          'reinvest_mode': '1',
          'reinverst_term': '6M',
          'draw_amount_per_term': 0,
          'to_draw_times': 0,
          'fixed_current_flag': '1',
          'interest_paid': 0,
          'refund_type': '03'
        }
      ]
    }
  }
}
