# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  private_lane :build do
    increment_build_number(xcodeproj: './ios/soga.xcodeproj')
    build_app(workspace: "./ios/soga.xcworkspace", scheme: "soga", export_xcargs: "-allowProvisioningUpdates")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    update_info_plist(
      plist_path: "soga/Info.plist",
      xcodeproj: "./ios/soga.xcodeproj",
      display_name: "Soga App Name",
      app_identifier: "test.soga"
    )
    build
    push_to_git_remote
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/soga.xcodeproj')
  end
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
  end
end
