export default {
  OP: 'CGI_PREFIX_OP', // 运营系统
  WEBANK: 'CGI_PREFIX', // 行内系统
  CDN: 'WEBANK_CDN', // CDN
  TENCENT_CGI_PREFIX: 'TENCENT_CGI_PREFIX',
  TENCENT_CGI_PREFIX2: 'TENCENT_CGI_PREFIX2',
  CGI_PREFIX_S: 'CGI_PREFIX_S',
  DATA_CGI_PREFIX: 'DATA_CGI_PREFIX',
  Q_CLOUD_FB: 'Q_CLOUD_FB',
  CS_CDN: 'CS_CDN',
  SDK_PREFIX: 'SDK_PREFIX',
  REMOTE_PAGE: 'REMOTE_PAGE',
  HTTPS_HTML_PREFIX: 'HTTPS_HTML_PREFIX',
  CGI_PREFIX_HJHTR: 'CGI_PREFIX_HJHTR',
  CDN_HJUPLOAD: 'CDN_HJUPLOAD'
}
